import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Button from "~/components/ui/Button";
import Navbar from "~/components/ui/Navbar";
import { NextPageWithLayout } from "./_app";
import Layout from "~/components/ui/Layout";
import UserAvatar from "~/components/ui/UserAvatar";
import MessageCard from "~/components/ui/Chat/ChatCard";
import Input from "~/components/ui/Input";

const Home: NextPageWithLayout = () => {
  const { status, data } = useSession();

  if (status !== "authenticated") {
    return <Link href={"/auth/login"}>Login with email and password</Link>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-12 flex w-[100%] gap-12 text-left">
        
      </main>
    </>
  );
};

export default Home;
Home.getLayout = (page: React.ReactElement) => {
  return <Layout>{page}</Layout>;
};

interface MessageBoxProps {
  left: boolean;
  content: string;
}
const MessageBox = ({ left, content }: MessageBoxProps) => {
  return (
    <section className={`${left ? "text-left" : "text-right"}`}>
      <div className="inline-block rounded-md bg-green-400 px-4 py-2 text-black ">
        {content}
      </div>
    </section>
  );
};
