import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Button from "~/components/ui/Button";
import Navbar from "~/components/ui/Navbar";
import { NextPageWithLayout } from "./_app";
import Layout from "~/components/ui/Layout";
import UserAvatar from "~/components/ui/UserAvatar";
import MessageCard from "~/components/ui/Chat/ChatCard";
import Input from "~/components/ui/Input";

const Home: NextPageWithLayout = () => {
  const { status, data } = useSession();

  if (status !== "authenticated") {
    return <Link href={"/auth/login"}>Login with email and password</Link>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-12 flex w-[100%] gap-12 text-left">
        <div className="rounded-lg border border-gray-600 px-4 py-4">
          {[1, 2, 3, 4, 5, 6, 7, 8].map((c, i) => (
            <MessageCard name="Suzan Rana" sub="How was the day?" />
          ))}
        </div>
        <div className="flex grow flex-col justify-between gap-8 rounded-lg px-4 py-4">
          <div className="flex cursor-pointer items-center  gap-4">
            <div className="h-8 w-8 rounded-full bg-white"></div>
            <h2> Suzan Rana</h2>
          </div>
          <div className="flex grow flex-col gap-4">
            <MessageBox content="Hello, world" left={true} />
            <MessageBox content="Hey, the world says Hello." left={false} />
            <MessageBox content="How is the weather so nice" left={true} />
            <MessageBox left={false} content="Always has been." />
          </div>

          <div className="flex gap-2 ">
            <Input className="py-6 pl-6" placeholder="Write a message..." />
            <Button>Send</Button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
Home.getLayout = (page: React.ReactElement) => {
  return <Layout>{page}</Layout>;
};

interface MessageBoxProps {
  left: boolean;
  content: string;
}
const MessageBox = ({ left, content }: MessageBoxProps) => {
  return (
    <section className={`${left ? "text-left" : "text-right"}`}>
      <div className="inline-block rounded-md bg-green-400 px-4 py-2 text-black ">
        {content}
      </div>
    </section>
  );
};
