export const CategoryEnum = {
  SCIENCE_AND_TECH: "SCIENCE_AND_TECH",
  COMEDY: "COMEDY",
  ENTERTAINMENT: "ENTERTAINMENT",
  AI: "AI",
  FRONTEND_DEVELOPMENT: "FRONTEND_DEVELOPMENT",
  BACKEND_DEVELOPMENT: "BACKEND_DEVELOPMENT",
  MARKETING: "MARKETING",
  ANIME: "ANIME",
  MOVIES: "MOVIES",
  CRYPTO_CURRENCY: "CRYPTO_CURRENCY",
} as const;

export const ReactionEnum = {
  HEART: "HEART",
  HAPPY: "HAPPY",
  SAD: "SAD",
} as const;
